sudo: required
dist: trusty
services:
  - docker
language: go
go:
  - 1.9.1
before_install:
  - sudo apt-get update -yq
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -yq docker-ce
script:
  - make docker-build
  - if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      docker login -u="${DOCKER_USER}" -p="${DOCKER_PASS}";
      make deploy;
    fi
notifications:
  email:
    recipients:
      - harsh@portworx.com
    on_success: always
    on_failure: always
