apiVersion: v1
kind: Secret
metadata:
  name: docker-reg-secret
  namespace: kube-system
type: Opaque
data:
  REGISTRY_USER: <base64-encode-of-docker-reg-use>
  REGISTRY_PASS: <base64-encode-of-docker-reg-password>
